export const queryKey = {
  POINTSLIST: 'pointsList',
  REVIEWSME: 'reviewList',
  HOMEDATA: 'homeData',
  HOMEMISSION: 'homeMission',
  ADDRESS: 'address',
  MISSIONSPROGRESS: 'missionsProgress',
  MISSIONSCOMPLETE: 'missionsComplete',
  USERINFO: 'userInfo',
  STOREINFO: 'storeInfo',
  STORELIST: 'storeList',
  STOREDATA: 'storeData',
  STOREREVIEWIMAGES: 'storeReviewImages',
  STOREREVIEWLIST: 'storeReviewList',
  NOTIFICATIONS: 'notifications',
  QUESTIONS: 'questions',
  QUESTIONDETAIL: 'questionDetail',
  SEARCH: 'search',
};
